/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedComandosRouteImport } from './routes/_authenticated/comandos'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEconomiaRouteImport } from './routes/_authenticated/economia'
import { Route as AuthenticatedInicializacaoRouteImport } from './routes/_authenticated/inicializacao'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedModeracaoRouteImport } from './routes/_authenticated/moderacao'
import { Route as AuthenticatedServidorRouteImport } from './routes/_authenticated/servidor'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated/tickets'
import { Route as ApiPublicDiscordInteractionsRouteImport } from './routes/api/public/discord/interactions'
import { Route as ApiPublicWorkerActionsRouteImport } from './routes/api/public/worker/actions'
import { Route as ApiPublicWorkerEventsRouteImport } from './routes/api/public/worker/events'
import { Route as ApiPublicWorkerHeartbeatRouteImport } from './routes/api/public/worker/heartbeat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedComandosRoute = AuthenticatedComandosRouteImport.update({
  id: '/comandos',
  path: '/comandos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEconomiaRoute = AuthenticatedEconomiaRouteImport.update({
  id: '/economia',
  path: '/economia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicializacaoRoute =
  AuthenticatedInicializacaoRouteImport.update({
    id: '/inicializacao',
    path: '/inicializacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModeracaoRoute = AuthenticatedModeracaoRouteImport.update({
  id: '/moderacao',
  path: '/moderacao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServidorRoute = AuthenticatedServidorRouteImport.update({
  id: '/servidor',
  path: '/servidor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicDiscordInteractionsRoute =
  ApiPublicDiscordInteractionsRouteImport.update({
    id: '/api/public/discord/interactions',
    path: '/api/public/discord/interactions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWorkerActionsRoute = ApiPublicWorkerActionsRouteImport.update({
  id: '/api/public/worker/actions',
  path: '/api/public/worker/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkerEventsRoute = ApiPublicWorkerEventsRouteImport.update({
  id: '/api/public/worker/events',
  path: '/api/public/worker/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkerHeartbeatRoute =
  ApiPublicWorkerHeartbeatRouteImport.update({
    id: '/api/public/worker/heartbeat',
    path: '/api/public/worker/heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comandos': typeof AuthenticatedComandosRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/economia': typeof AuthenticatedEconomiaRoute
  '/inicializacao': typeof AuthenticatedInicializacaoRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/moderacao': typeof AuthenticatedModeracaoRoute
  '/servidor': typeof AuthenticatedServidorRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/api/public/discord/interactions': typeof ApiPublicDiscordInteractionsRoute
  '/api/public/worker/actions': typeof ApiPublicWorkerActionsRoute
  '/api/public/worker/events': typeof ApiPublicWorkerEventsRoute
  '/api/public/worker/heartbeat': typeof ApiPublicWorkerHeartbeatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comandos': typeof AuthenticatedComandosRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/economia': typeof AuthenticatedEconomiaRoute
  '/inicializacao': typeof AuthenticatedInicializacaoRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/moderacao': typeof AuthenticatedModeracaoRoute
  '/servidor': typeof AuthenticatedServidorRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/api/public/discord/interactions': typeof ApiPublicDiscordInteractionsRoute
  '/api/public/worker/actions': typeof ApiPublicWorkerActionsRoute
  '/api/public/worker/events': typeof ApiPublicWorkerEventsRoute
  '/api/public/worker/heartbeat': typeof ApiPublicWorkerHeartbeatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/comandos': typeof AuthenticatedComandosRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/economia': typeof AuthenticatedEconomiaRoute
  '/_authenticated/inicializacao': typeof AuthenticatedInicializacaoRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/moderacao': typeof AuthenticatedModeracaoRoute
  '/_authenticated/servidor': typeof AuthenticatedServidorRoute
  '/_authenticated/tickets': typeof AuthenticatedTicketsRoute
  '/api/public/discord/interactions': typeof ApiPublicDiscordInteractionsRoute
  '/api/public/worker/actions': typeof ApiPublicWorkerActionsRoute
  '/api/public/worker/events': typeof ApiPublicWorkerEventsRoute
  '/api/public/worker/heartbeat': typeof ApiPublicWorkerHeartbeatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/comandos'
    | '/configuracoes'
    | '/dashboard'
    | '/economia'
    | '/inicializacao'
    | '/logs'
    | '/moderacao'
    | '/servidor'
    | '/tickets'
    | '/api/public/discord/interactions'
    | '/api/public/worker/actions'
    | '/api/public/worker/events'
    | '/api/public/worker/heartbeat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/comandos'
    | '/configuracoes'
    | '/dashboard'
    | '/economia'
    | '/inicializacao'
    | '/logs'
    | '/moderacao'
    | '/servidor'
    | '/tickets'
    | '/api/public/discord/interactions'
    | '/api/public/worker/actions'
    | '/api/public/worker/events'
    | '/api/public/worker/heartbeat'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/comandos'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/economia'
    | '/_authenticated/inicializacao'
    | '/_authenticated/logs'
    | '/_authenticated/moderacao'
    | '/_authenticated/servidor'
    | '/_authenticated/tickets'
    | '/api/public/discord/interactions'
    | '/api/public/worker/actions'
    | '/api/public/worker/events'
    | '/api/public/worker/heartbeat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicDiscordInteractionsRoute: typeof ApiPublicDiscordInteractionsRoute
  ApiPublicWorkerActionsRoute: typeof ApiPublicWorkerActionsRoute
  ApiPublicWorkerEventsRoute: typeof ApiPublicWorkerEventsRoute
  ApiPublicWorkerHeartbeatRoute: typeof ApiPublicWorkerHeartbeatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/comandos': {
      id: '/_authenticated/comandos'
      path: '/comandos'
      fullPath: '/comandos'
      preLoaderRoute: typeof AuthenticatedComandosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/economia': {
      id: '/_authenticated/economia'
      path: '/economia'
      fullPath: '/economia'
      preLoaderRoute: typeof AuthenticatedEconomiaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicializacao': {
      id: '/_authenticated/inicializacao'
      path: '/inicializacao'
      fullPath: '/inicializacao'
      preLoaderRoute: typeof AuthenticatedInicializacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/moderacao': {
      id: '/_authenticated/moderacao'
      path: '/moderacao'
      fullPath: '/moderacao'
      preLoaderRoute: typeof AuthenticatedModeracaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/servidor': {
      id: '/_authenticated/servidor'
      path: '/servidor'
      fullPath: '/servidor'
      preLoaderRoute: typeof AuthenticatedServidorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/discord/interactions': {
      id: '/api/public/discord/interactions'
      path: '/api/public/discord/interactions'
      fullPath: '/api/public/discord/interactions'
      preLoaderRoute: typeof ApiPublicDiscordInteractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/actions': {
      id: '/api/public/worker/actions'
      path: '/api/public/worker/actions'
      fullPath: '/api/public/worker/actions'
      preLoaderRoute: typeof ApiPublicWorkerActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/events': {
      id: '/api/public/worker/events'
      path: '/api/public/worker/events'
      fullPath: '/api/public/worker/events'
      preLoaderRoute: typeof ApiPublicWorkerEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/heartbeat': {
      id: '/api/public/worker/heartbeat'
      path: '/api/public/worker/heartbeat'
      fullPath: '/api/public/worker/heartbeat'
      preLoaderRoute: typeof ApiPublicWorkerHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedComandosRoute: typeof AuthenticatedComandosRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEconomiaRoute: typeof AuthenticatedEconomiaRoute
  AuthenticatedInicializacaoRoute: typeof AuthenticatedInicializacaoRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedModeracaoRoute: typeof AuthenticatedModeracaoRoute
  AuthenticatedServidorRoute: typeof AuthenticatedServidorRoute
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedComandosRoute: AuthenticatedComandosRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEconomiaRoute: AuthenticatedEconomiaRoute,
  AuthenticatedInicializacaoRoute: AuthenticatedInicializacaoRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedModeracaoRoute: AuthenticatedModeracaoRoute,
  AuthenticatedServidorRoute: AuthenticatedServidorRoute,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicDiscordInteractionsRoute: ApiPublicDiscordInteractionsRoute,
  ApiPublicWorkerActionsRoute: ApiPublicWorkerActionsRoute,
  ApiPublicWorkerEventsRoute: ApiPublicWorkerEventsRoute,
  ApiPublicWorkerHeartbeatRoute: ApiPublicWorkerHeartbeatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
